package com.pickteam.util;

public enum VideoConferenceControlMsg {
    GET_PARTICIPANTS, GET_PARTICIPANTS_CONFIRMED, START_SCREEN_SHARING, START_SCREEN_SHARING_CONFIRMED,
    STOP_SCREEN_SHARING, STOP_SCREEN_SHARING_CONFIRM, STOP_SCREEN_SHARING_CONFIRMED,SHOULD_OUT_CHANNEL
}
